export const ENTIDADES = [
  {
    orden: 0,
    key: 'sector',
    sigla: 'Sector',
    nombre: 'Sector',
    sector: 'CRD',
    color: '#FAFAFA',
  },
  {
    orden: 1,
    key: 'scrd',
    sigla: 'SCRD',
    nombre: 'SCRD',
    sector: 'CRD',
    color: '#FAFAFA',
  },
  {
    orden: 2,
    key: 'ofb',
    sigla: 'OFB',
    nombre: 'OFB',
    sector: 'CRD',
    color: '#FAFAFA',
  },
  {
    orden: 3,
    key: 'idpc',
    sigla: 'IDPC',
    nombre: 'IDPC',
    sector: 'CRD',
    color: '#FAFAFA',
  },
  {
    orden: 5,
    key: 'idartes',
    sigla: 'IDARTES',
    nombre: 'IDARTES',
    sector: 'CRD',
    color: '#FAFAFA',
  },
  {
    orden: 6,
    key: 'idrd',
    sigla: 'IDRD',
    nombre: 'IDRD',
    sector: 'CRD',
    color: '#FAFAFA',
  },
  {
    orden: 8,
    key: 'fuga',
    sigla: 'FUGA',
    nombre: 'FUGA',
    sector: 'CRD',
    color: '#FAFAFA',
  },
  {
    orden: 9,
    key: 'canal capital',
    sigla: 'Canal Capital',
    nombre: 'Canal Capital',
    sector: 'CRD',
    color: '#FAFAFA',
  },
  {
    orden: 20,
    key: 'idpyba',
    sigla: 'IDPYBA',
    nombre: 'IDPYBA',
    sector: 'Ambiente',
    color: '#FAFAFA',
  },
  {
    orden: 21,
    key: 'metro',
    sigla: 'Metro',
    nombre: 'Metro',
    sector: 'Movilidad',
    color: '#FAFAFA',
  },
]
